CREATE INDEX IF NOT EXISTS idx_users_org_branch ON users(organization_id, branch_id);
CREATE INDEX IF NOT EXISTS idx_customers_org_branch ON customers(organization_id, branch_id);
CREATE INDEX IF NOT EXISTS idx_customers_mobile ON customers(mobile);
CREATE INDEX IF NOT EXISTS idx_customers_status ON customers(customer_status);
CREATE INDEX IF NOT EXISTS idx_customers_pan ON customers(pan_number);
CREATE INDEX IF NOT EXISTS idx_customers_gst ON customers(gst_number);
CREATE INDEX IF NOT EXISTS idx_customers_trgm_name ON customers USING GIN (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_customers_trgm_company ON customers USING GIN (company_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_vehicles_org_branch ON vehicles(organization_id, branch_id);
CREATE INDEX IF NOT EXISTS idx_vehicles_customer ON vehicles(customer_id);
CREATE INDEX IF NOT EXISTS idx_vehicles_registration ON vehicles(registration_number);
CREATE INDEX IF NOT EXISTS idx_vehicles_expiry ON vehicles(insurance_expiry);
CREATE INDEX IF NOT EXISTS idx_vehicles_trgm_reg ON vehicles USING GIN (registration_number gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_policies_org_branch ON policies(organization_id, branch_id);
CREATE INDEX IF NOT EXISTS idx_policies_customer ON policies(customer_id);
CREATE INDEX IF NOT EXISTS idx_policies_vehicle ON policies(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_policies_company ON policies(insurance_company_id);
CREATE INDEX IF NOT EXISTS idx_policies_status ON policies(status);
CREATE INDEX IF NOT EXISTS idx_policies_end_date ON policies(end_date);
CREATE INDEX IF NOT EXISTS idx_live_quotations_customer ON live_quotations(customer_id);
CREATE INDEX IF NOT EXISTS idx_live_quotations_company ON live_quotations(insurance_company_id);
CREATE INDEX IF NOT EXISTS idx_claims_policy ON claims(policy_id);
CREATE INDEX IF NOT EXISTS idx_claims_status ON claims(status);
CREATE INDEX IF NOT EXISTS idx_rto_services_customer ON rto_services(customer_id);
CREATE INDEX IF NOT EXISTS idx_rto_services_due_date ON rto_services(due_date);
CREATE INDEX IF NOT EXISTS idx_finance_customer ON finance_records(customer_id);
CREATE INDEX IF NOT EXISTS idx_leads_assigned_to ON leads(assigned_to);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(status);
CREATE INDEX IF NOT EXISTS idx_leads_next_follow_up ON leads(next_follow_up_date);
CREATE INDEX IF NOT EXISTS idx_follow_ups_customer ON follow_ups(customer_id);
CREATE INDEX IF NOT EXISTS idx_follow_ups_reminder ON follow_ups(reminder_at);
CREATE INDEX IF NOT EXISTS idx_payments_payment_date ON payments(payment_date);
CREATE INDEX IF NOT EXISTS idx_payments_mode ON payments(payment_mode);
CREATE INDEX IF NOT EXISTS idx_renewals_due_date ON renewals(due_date);
CREATE INDEX IF NOT EXISTS idx_documents_customer ON documents(customer_id);
CREATE INDEX IF NOT EXISTS idx_whatsapp_customer ON whatsapp_reminder_logs(customer_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_user ON activity_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at ON activity_logs(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_policies_customer_status ON policies(customer_id, status);
CREATE INDEX IF NOT EXISTS idx_renewals_customer_due ON renewals(customer_id, due_date);
CREATE INDEX IF NOT EXISTS idx_leads_branch_status ON leads(branch_id, status);
CREATE INDEX IF NOT EXISTS idx_claims_customer_status ON claims(customer_id, status);
