ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE insurance_companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE live_quotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE rto_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE follow_ups ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE commissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE renewals ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_reminder_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY org_access ON organizations FOR ALL USING (id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY branch_access ON branches FOR ALL USING (organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY user_access ON users FOR ALL USING (id = auth.uid() OR organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY customer_access ON customers FOR ALL USING (organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY vehicle_access ON vehicles FOR ALL USING (organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY company_access ON insurance_companies FOR ALL USING (organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY policy_access ON policies FOR ALL USING (organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY quotation_access ON live_quotations FOR ALL USING (organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY claim_access ON claims FOR ALL USING (organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY rto_access ON rto_services FOR ALL USING (organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY finance_access ON finance_records FOR ALL USING (organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY lead_access ON leads FOR ALL USING (organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY follow_up_access ON follow_ups FOR ALL USING (organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY payment_access ON payments FOR ALL USING (organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY expense_access ON expenses FOR ALL USING (organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY commission_access ON commissions FOR ALL USING (organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY renewal_access ON renewals FOR ALL USING (organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY document_access ON documents FOR ALL USING (organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY whatsapp_access ON whatsapp_reminder_logs FOR ALL USING (organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
CREATE POLICY activity_access ON activity_logs FOR ALL USING (organization_id IN (SELECT organization_id FROM users WHERE id = auth.uid()));
